server:
  port: 8082
spring:
  application:
    name: eureka-client
instance:
  metadata-map.zone: zone2
  client:
    register-with-eureka: true
    fetch-registry: true #如果为true，启动时告警
    service-url:
      zone1: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      zone2: http://localhost:8763/eureka/,http://localhost:8764/eureka/
    region: region-east
    availability-zones:
      region-east: zone1,zone2